import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyFooter from "./Components/MyFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const enlacesFooter = [
    <a href="/" className="m-1">
      Info
    </a>,
    <a href="/" className="m-1 text-gray-500">
      ·
    </a>,
    <a href="/" className="m-1">
      Support
    </a>,
    <a href="/" className="m-1 text-gray-500">
      ·
    </a>,
    <a href="/" className="m-1">
      Marketing
    </a>,
    <a href="/" className="m-1">
      Terms of Use
    </a>,
    <a href="/" className="m-1 text-gray-500">
      ·
    </a>,
    <a href="/" className="m-1">
      Privacy Policy
    </a>,
  ];

  let svgsEnlaces = [
    <a href="https://es-la.facebook.com/" target="_blank">
      <img src="facebook.svg"></img>
    </a>,

    <a
      href="https://www.instagram.com/accounts/login/?__coig_restricted=1"
      target="_blank"
    >
      <img src="instagram.svg"></img>
    </a>,
    <a
      href="https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoiZXMifQ%3D%3D%22%7D"
      target="_blank"
    >
      <img src="twitter.svg"></img>
    </a>,
  ];
  return (
    <html lang="en">
      <head>
        <title>myPet</title>
      </head>
      <body className={inter.className}>
        <header></header>
        <main>{children}</main>
        <footer>
          <MyFooter enlacesFooter={enlacesFooter} svgsEnlaces={svgsEnlaces} />
        </footer>
      </body>
    </html>
  );
}
